"use client";
import Head from "next/head";
import { CircularProgress, Container, Stack, ThemeProvider, Typography } from "@mui/material";
import ListView from "@/components/ListView";
import { theme } from "@/theme";
import Settings from "@/components/Settings";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { load } from "@/services/LoadService";
import { useAppStore } from "@/services/store";
import { useShallow } from "zustand/shallow";

export default function List() {
  const router = useRouter();
  const store = useAppStore(useShallow((state) => state));

  const { listResponse, unitSizeMultipliers } = store;

  const armyPtsTotal = listResponse?.units
    .map((x) => {
      const sizeMultiplier = unitSizeMultipliers.find((m) => m.unitId === x.selectionId)?.multiplier || 1;
      return x.cost * sizeMultiplier;
    })
    .reduce((acc, curr) => acc + curr, 0);

  useEffect(() => {
    if (router.isReady) {
      const listId = router.query["id"]?.toString();

      if (listId) {
        load(store, listId);
      }
    }
  }, [router.isReady]);

  return (
    <>
      <Head>
        <title>OPR GFF/AoFS - Beefy Mode</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <Container sx={{ pt: 2 }}>
          {store.loading && <CircularProgress />}
          <Stack direction="row" justifyContent="space-between" alignItems="center" mb={2}>
            <Settings />
            <Typography variant="h5">List total: {armyPtsTotal}pts</Typography>
          </Stack>
          <ListView />
        </Container>
      </ThemeProvider>
    </>
  );
}
